version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8080:8080"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    depends_on:
      - backend 